name: .NET Core Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./Lab_8_KTNC_Khangdhpc08188.sln

      - name: Build project
        run: dotnet build ./Lab_8_KTNC_Khangdhpc08188.sln --no-restore

      - name: Run tests
        run: dotnet test ./Lab_8_KTNC_Khangdhpc08188.sln --no-build --verbosity normal
